In [6]:
#comprehensions
def dictionarykeyfile(keyfile):
    key={}
    with open(keyfile,'r')as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key
dictionarykeyfile('DataFiles/key.txt')
keyfile='DataFiles/key.txt'
key=dictionarykeyfile(keyfile)
evenkeys={item for item in key}
evenkeys

{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}

### Numpy Library

- Processing N-Dimensional arrays


In [5]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
a
type(a)
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
rn=np.random.randint(0,100,size=10)
rn

array([26, 89, 39, 86, 18, 13, 79, 56, 41, 61])

In [16]:
m3=np.random.randint(0,2,size=(3,3))
m3
m3[0][2]

array([[1, 1, 1],
       [0, 1, 0],
       [0, 1, 0]])

In [17]:
m3=np.random.randint(0,2,size=(3,3,3))
m3

array([[[1, 1, 0],
        [0, 1, 1],
        [0, 1, 0]],

       [[0, 0, 0],
        [1, 0, 1],
        [0, 0, 1]],

       [[1, 1, 0],
        [1, 1, 1],
        [0, 1, 0]]])

In [20]:
m3=np.random.randint(0,2,size=(3,3,3,3))
m3
m3[2][2][2][2]
m3

array([[[[1, 1, 0],
         [0, 1, 1],
         [1, 0, 1]],

        [[1, 0, 1],
         [0, 0, 1],
         [0, 0, 0]],

        [[0, 1, 1],
         [1, 0, 1],
         [1, 1, 0]]],


       [[[0, 1, 0],
         [1, 0, 1],
         [0, 0, 0]],

        [[0, 0, 1],
         [1, 0, 0],
         [1, 0, 1]],

        [[0, 1, 1],
         [0, 1, 0],
         [1, 0, 0]]],


       [[[1, 0, 0],
         [0, 1, 0],
         [0, 1, 1]],

        [[1, 1, 0],
         [0, 1, 0],
         [0, 1, 0]],

        [[1, 1, 1],
         [1, 0, 1],
         [1, 1, 0]]]])

In [21]:
m3.ndim # dimensions of array

4

In [22]:
m3.size # size of array -> how many elements

81

In [23]:
m3.shape  # 

(3, 3, 3, 3)

In [24]:
m3.dtype  # Data type

dtype('int32')

In [25]:
m3.itemsize

4

In [26]:
m3.nbytes

324

## Numpy 

- Numpy is the functional 

In [27]:
import numpy as np     # Importing Libraries

a=np.array([0,1,2])
b=np.array([5,5,5])

print("Matrix A\n",a)
print("Matrix B\n",b)

print("Regular matrix addition A+B\n",a+b)
print("Addition using Broadcasting A+5\n",a+5)


Matrix A
 [0 1 2]
Matrix B
 [5 5 5]
Regular matrix addition A+B
 [5 6 7]
Addition using Broadcasting A+5
 [5 6 7]


In [29]:
c=b.reshape(5,3)
c

ValueError: cannot reshape array of size 3 into shape (5,3)

In [28]:
d=c+1

NameError: name 'c' is not defined

In [35]:
c=np.array([0,1,2],[3,4,5],[6,7,8])
d=np.array([[1,2,3],[1,2,3],[1,2,3]])

e=np.array([1,2,3])

print("Matrix\n",c)
print("Matrix\n",d)
print("Matrix\n",e)

print("Regular matrix addition\n",c+d)
print("Addition using Broadcating\n",c+e)

ValueError: only 2 non-keyword arguments accepted

In [32]:
import numpy as np
m=np.ones((3,3))
print("matrix M:\n",m)

matrix M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
import numpy as np
npm_a=np.array(mat_b)
npm_b=np.array(mat_a)

NameError: name 'mat_b' is not defined

### Pandas

Usecases
- Data cleaning
- Data Transformation
- Data Analysis

Notations
- series  It is a row
- DataFrames   It is a table


In [2]:
import pandas as pd

internal1={'s1':21,'s2':18,'s3':24}

internal1=pd.Series(internal1)

internal2={'s1':15,'s2':18,'s3':12}

internal2=pd.Series(internal2)

internal2



s1    15
s2    18
s3    12
dtype: int64

In [4]:
final={'Internal':internal1,'Internal2':internal2}

final=pd.DataFrame(final)
final

Internal  Internal2
s1        21         15
s2        18         18
s3        24         12

In [12]:
final={'Internal1':internal1,'Internal2':internal2}

final=pd.DataFrame(final)
final('Internal1')

TypeError: 'DataFrame' object is not callable

In [8]:
final.columns  # Names of all columns

Index(['Internal', 'Internal2'], dtype='object')

In [9]:
final.values  # Listsof all rows

array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [13]:
final.values[2]

array([24, 12], dtype=int64)

In [16]:
final.values[2,0]
final.values[2][0]

24

In [17]:
for row in final.values:
    print('Internal1 - ',row[0],'Internal2 -',row[1])

Internal1 -  21 Internal2 - 15
Internal1 -  18 Internal2 - 18
Internal1 -  24 Internal2 - 12


In [18]:
final.loc[3]=[15,18]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
3          15         18

In [19]:
final.drop(3)

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [20]:
final.drop(s2)

NameError: name 's2' is not defined

In [21]:
final=final.drop(3)
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [22]:
final.values[2]=[12,25]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         12         25